name: 'Load Container Action'

description: 'Imports the image build caches and loads them for Docker CLI'

inputs:
  repo:
    description: 'Input string that gets passed along to the docker build args'
    required: true
  tag_list:
    description: 'List of tags that gets passed along to the docker build args'
    required: true
    default: '' # set to an empty string
