name: 'Load Container Action'

description: 'Imports the image build caches and loads them for Docker CLI'

inputs:
  repo:
    description: 'Input string that gets passed along to the docker build args'
    required: true
  tag_list:
    description: 'List of tags that gets passed along to the docker build args'
    required: true
    default: '' # set to an empty string

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2

  - name: Generate tag list
    id: generate-tag-list
    env:
      REPO: ${{ inputs.repo }}
    run: |
      docker_repo=${GITHUB_REPOSITORY/opensciencegrid\/docker-/opensciencegrid/}
      if [ -z "${{ inputs.tag_list }}" ]; then
        tag_list=$docker_repo:$REPO,$docker_repo:$(date +%Y%m%d-%H%M)
      else
        tag_list=${{ inputs.tag_list }}
      fi
      echo "::set-output name=taglist::$tag_list"
    shell: bash

  - name: Import Docker images from cache
    uses: actions/cache@v2
    with:
      path: /tmp/.buildx-cache
      key: ${{ inputs.repo }}-buildx-${{ github.sha }}-${{ github.run_id }}

  - name: Load Docker images for use in Docker CLI
    uses: docker/build-push-action@v2.2.2
    with:
      push: False
      context: .
      build-args: BASE_YUM_REPO=${{ inputs.repo }}
      load: True # allow acces to built images through the Docker CLI
      tags: ${{ inputs.taglist }}
      cache-from: type=local,src=/tmp/.buildx-cache
      cache-to: type=local,src=/tmp/.buildx-cache
